project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "!IDEAS.md"

website:
  title: "Dr. Steffi LaZerte"
  site-url: https://steffilazerte.ca
  description: "Tips & Tricks"
  favicon: "images/logo_gear.png"
  navbar:
    pinned: true
    logo: "/images/logo_gear.png"
    right:
      - text: "Home"
        file: index.qmd
      - R.qmd
      - cv.qmd
      - presentations.qmd
      - tips_and_tricks.qmd
      - text: "About"
        file: about.qmd
      - icon: envelope
        href: mailto:sel@steffilazerte.ca
      - icon: github
        href: https://github.com/steffilazerte
      - icon: twitter
        href: https://twitter.com/steffilazerte
      - icon: mastodon
        href: https://fosstodon.org/@steffilazerte
format:
  html:
    includes:
      in_header: header.html
    theme:
      - simplex
      - styles.scss

execute:
  echo: false
  message: false

