---
title: R Projects
toc: true
---

```{r, include = FALSE}
source("pre-render.R")
```

## Package Developement

```{r}
jobs %>%
  filter(type == "package") %>%
  mutate(pkg = str_extract(title, "\\w+"),
         title = tt(title, type = "html"), 
         end2 = if_else(is.na(end), "999999999", end),
         ) %>%
  arrange(!is.na(end), desc(end2), desc(start)) %>%
  select(-skills) %>%
  fmt_pkgs(type = "html") %>%
  fmt_gt()
```

## R Script Development and Analysis

```{r}
jobs %>%
  filter(type %in% c("analysis", "programming")) %>%
  select(-skills) %>%
  fmt_pkgs(type = "html", ignore_consultant = TRUE) %>%
  fmt_gt() %>%
  cols_width(title ~ "25%")
```

## R Workshops

```{r}
jobs %>%
  filter(type == "r workshop") %>%
  mutate(title = str_remove(title, " Workshop")) %>%
  fmt_teaching(type = "html") %>%
  fmt_gt()
```

## Other R-related work

```{r}
jobs %>%
  filter(type %in% c("r jobs")) %>%
  select(-skills) %>%
  fmt_pkgs(type = "html") %>%
  fmt_gt()
```

See my CV for more details on [Teaching R](cv.html#r-university-teaching), and 
[R Volunteering](cv.html#r-volunteering)

