---
layout: default
title: Teaching and Outreach
weight: 4
---

I find teaching and sharing my research with others immensely gratifying. In the past I have hosted R Coffee Hours and the corresponding [ThinkR website](../thinkR/) as a way of helping students working with R statistical software. Further, as most research is publicly funded, to some degree I consider outreach and education a social responsibility. I enjoy having discussions about research and sharing or inspiring exciting and interesting ideas. I also enjoy hearing about new and interesting ideas or concerns about research. I have, therefore, deliberately sought opportunities to both improve my teaching skills and share the results of my research with interested parties.

For a list of teaching related activities see the [Teaching]({{ site.baseurl }}/skills/#teaching) section of my CV.

For a list of outreach related activities see the [Outreach]({{ site.baseurl }}/skills/#community-presentations-and-outreach) section of my CV.
